### ISSUE TITLE
Need to sort by seeds

### ISSUE THREAD

**Issue by deathbat6661** [Ryuk-me/Torrents-Api#10]
Hi, I need to sort by seed all torrent result data, it's possible? Yts result have no seed data

Just check rarbg not supported to search by imdb id, while the rarbg search website can be found by imdb id. Is the search url is different than the search on website?

**Comment by Ryuk-me** [comment]
I will try to implement sort by seeds (this can be implemented on sites which allows sort by seeds / shows seeders)
and search by imdb id is working on torrent galaxy  but its not working on rarbg site 
can u please share a working imdb id on rarbg site.
YTS doesn't show seeders / leechers of their torrent.
