### ISSUE TITLE
ettv gives an IP address error on heroku

### ISSUE THREAD

**Issue by Inside4ndroid** [Ryuk-me/Torrents-Api#13]
i have deployed to heroku but the ettv returns an error which is 

"{"error":"Website is blocked change IP"}"

can this be fixed or is it my local ip thats bloacked??

Thanks

**Comment by Ryuk-me** [comment]
ettv website is blocked on heroku

**Comment by Inside4ndroid** [comment]
ahh i see okay thank you for clearing that up i guess i will have to run it on my dedicated server instead then :)

Thank You!
