### ISSUE TITLE
Some problems with torlock and all

### ISSUE THREAD

**Issue by VarnaX-279** [Ryuk-me/Torrents-Api#14]
For some searches give some error for torlock and all

Ex:- https://torrents-api.ryukme.repl.co/api/torlock/rise%20of%20the%20planet%20of%20the%20apes
Ex:- https://torrents-api.ryukme.repl.co/api/all/rise%20of%20the%20planet%20of%20the%20apes

**Comment by Ryuk-me** [comment]
problem is with the hosting tried on local working fine.
