### ISSUE TITLE
Search by imdb/tmdb?

### ISSUE THREAD

**Issue by jakeround** [Ryuk-me/Torrents-Api#16]
Hello,

Looking to be able to search directly via a imdb/tmdb value? Seems like that way it would offer to search for a specific torrent rather than taking a guess by searching by a title string?

Thanks

**Comment by Ryuk-me** [comment]
@jakeround you can already do this
ex : https://torrents-api.ryukme.repl.co/api/tgx/tt0111161
but it does not work on every site.
