### ISSUE TITLE
[feature request] add bitsearch

### ISSUE THREAD

**Issue by yadianluffy** [Ryuk-me/Torrents-Api#17]
hello good job with the torrent search api could you add this site to the list

https://bitsearch.to/

**Comment by Ryuk-me** [comment]
@yadianluffy yeah sure

**Comment by yadianluffy** [comment]
ohhh thank you very much appreciated

**Comment by Ryuk-me** [comment]
@yadianluffy added bitsearch scrapper [Check Here](https://github.com/Ryuk-me/Torrents-Api/commit/5c049f88f6078ec4b225f2da23c4e1f78091852a)

**Comment by yadianluffy** [comment]
thank you you are the best
