### ISSUE TITLE
[feature request] torrent sites

### ISSUE THREAD

**Issue by yadianluffy** [Ryuk-me/Torrents-Api#18]
hello I bring you several torrents sites to add to this wonderful repo that is very useful to me thank you

https://glodls.to/home.php
https://www.magnetdl.com/
https://torrents-csv.ml/#/
https://www.limetorrents.pro/home/
https://www.torrentfunk.com/
https://demonoid.is/
https://torrentproject2.com/

you don't have to add them all, just as many as you can.

**Comment by Ryuk-me** [comment]
@yadianluffy i will try to add them

**Comment by yadianluffy** [comment]
thanks

**Comment by Ryuk-me** [comment]
@yadianluffy added most the sites
torrents-csv has its own api.
