### ISSUE TITLE
torrentFunk issue

### ISSUE THREAD

**Issue by Rajveer0916** [Ryuk-me/Torrents-Api#20]
torrentFunk url or torrent not showing in search results plz see it

**Comment by Ryuk-me** [comment]
@Rajveer0916 issue is with the website [see here](https://www.torrentfunk.com/torrent/22210244/avengers-endgame-2019-1080p-yts-lt.html)

**Comment by Rajveer0916** [comment]
Ohkk means their is no way by the way tnnqq for this repo love your work bro plz add those requested sites i also love them

**Comment by Ryuk-me** [comment]
@Rajveer0916 yeah sure i will add them

**Comment by Rajveer0916** [comment]
Bro magnetdl block in your demo link plz host your demo link where it unblock plz
