### ISSUE TITLE
Magnetdl block

### ISSUE THREAD

**Issue by Rajveer0916** [Ryuk-me/Torrents-Api#21]
Bro magnetdl block in your demo link plz host your demo link where it unblock plz

**Comment by Ryuk-me** [comment]
@Rajveer0916 it is because of the ddos protection will try to fix it

**Comment by Rajveer0916** [comment]
Bro plzz i lovee this project plz do something to fix it

**Comment by Ryuk-me** [comment]
@Rajveer0916 i have already fixed it wait till tomorrow i will upload a new repo

**Comment by Ryuk-me** [comment]
@Rajveer0916 https://github.com/Ryuk-me/Torrent-Api-py
