### ISSUE TITLE
Error in Torlock js

### ISSUE THREAD

**Issue by Inside4ndroid** [Ryuk-me/Torrents-Api#22]
hi everytime i call the /all/api/moviename i am getting the below output on the server

` UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of null
    at Promise.all.links.map (/var/www/vhosts/stupefied-pascal.212-227-214-107.plesk.page/httpdocs/Torrents-Api/torrent/torLock.js:42:96)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:1213066) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:1213066) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

any help on a fix would be great :)

Thanks

EDIT i commented out lines 42 and 54 in torlock js which seems to make it work but without uploader info.

**Comment by Ryuk-me** [comment]
@Inside4ndroid fixed it. 974c665759c48a50d6941fff1d819adb04201729
