### ISSUE TITLE
Limit results

### ISSUE THREAD

**Issue by devillD** [Ryuk-me/Torrents-Api#28]
Add the feature of limiting torrent results in a page.
e.g: /api/:website/:limit/:query/:page?

**Comment by Ryuk-me** [comment]
@devillD i am currently busy with my college exams, i can only add this after 5th march.

**Comment by Ryuk-me** [comment]
@devillD can u please switch to this repo [Torrent-Api-py](https://github.com/Ryuk-me/Torrent-Api-py) (already have limit option)
i may not be able to add this feature in this repo anytime soon
