### ISSUE TITLE
Add ability to make a combined query in all sites 

### ISSUE THREAD

**Issue by xd003** [Ryuk-me/Torrents-Api#4]
I think it would be great if there's a ability to make a combined query with all torrent sites at once . Unless a very specific reason , most people would anyways use it this way
Even all torrent aggregator sites typically have option to make a combined query or search in a torrent site specially

**Comment by Ryuk-me** [comment]
yeah sure will add that option too.

**Comment by Ryuk-me** [comment]
Done @xd003
